### ISSUE TITLE
How to run the code on my own testing set? 

### ISSUE THREAD

**Issue by cuicathy** [brainvisa/morpho-deepsulci#4]
Thanks for your amazing work! But I wonder that is the testing.py and the trained model provided?  I would like to implement your method on my own dataset to extract the sulci. 

Thank you! 
Cathy

**Comment by denisri** [comment]
The trained model will be usable in the upcoming version of Morphologist in [BrainVisa](http://brainvisa.info). We haven't had time to release it yet, but are currently working on it.

**Comment by cuicathy** [comment]
Good to know this. Thank you.

**Comment by LeonieBorne** [comment]
Hi @cuicathy! Thank you very much for your interest in this work!
The trained model is indeed not usable yet in the last release of Morphologist in Brainvisa, but to apply the model via docker you can use the information described here:
[https://github.com/LeonieBorne/morpho-deepsulci-docker](https://github.com/LeonieBorne/morpho-deepsulci-docker)
If you are interested, you will be one of the first to try to follow my instructions so don't hesitate if you have any questions!
I'm sorry for my late answer, I didn't see your question until now.
